### ISSUE TITLE
Actively being maintained?

### ISSUE THREAD

**Issue by jareddellitt** [dcrck/solana-elixir#1]
Noticed this hasn't been touched in a couple of years and wanted to check to see if this was going to be actively maintained or it was more of a one-off experiment/project.

**Comment by dcrck** [comment]
Hi there!

I made this for myself while I was actively working on Solana-related projects for my job. Once that job ended, I no longer had a reason to continue developing this (along with `solana-spl-elixir`). I'm happy to take PRs, or you can fork this repository for your own work.

Thanks for understanding.
